### ISSUE TITLE
Change code to use adapter logic

### ISSUE THREAD

**Issue by sebastianknopf** [sebastianknopf/tripmonitor#6]
Currently the only available input adapter is TRIAS (VDV 431). In future, there should be a possibility to add other adapters too. An adapter logic should be implemented to rnsure this.

- [x] Change configuration to receive an adapter type by name
- [x] Change configuration to hold adapter specific configurations (for vdv431 only endpoint and requestor_ref)
- [x] Implement vdv431 adapter.py
- [x] Move request.py, response.py to stopmonitor/adapter/vdv431/ 
- [x] Move implementation to vdv431/adapter.py and adapt references
- [x] Add dynamic loading of adapters only based on their name provided in configuration
- [x] Test ...

**Comment by sebastianknopf** [comment]
Configuration should look like:

```
adapter:
  type: vdv431
  params:
    endpoint: "YourServerEndpoint"
    requestor_ref: "YourRequestorRef"
```

Check whether the toplevel key `app` is still needed or not?
